### PR TITLE
Bump upstream

### PR DESCRIPTION
**Pull request by poemonsense**

### CODE REVIEW

**Comment by poemonsense** [comment]
@xiaokamikami I merge the upstream Spike. Would mind check whether this version works?

**Comment by xiaokamikami** [comment]
> @xiaokamikami I merge the upstream Spike. Would mind check whether this version works?

Ok, I will test it with nemu as ref

**Comment by poemonsense** [comment]
Force pushed to fix a macro definition bug.

**Comment by poemonsense** [comment]
However, it seems there are still some compiling errors. The APIs have changed again

**Comment by poemonsense** [comment]
Push a commit to fix the constructor of `cfg_t`.

There is still one compiling error in `difftest.cc:382` that should be fixed, i.e., the `plugin_device_factories` argument of `sim_t` that replaces the previous `plugin_devices`. It seems it accepts a vector of factory classes which further initiates the devices. I don't find easily how the factory is built with a base address. Hopefully you can have a try @xiaokamikami

**Comment by xiaokamikami** [comment]
> Push a commit to fix the constructor of `cfg_t`.
> 
> There is still one compiling error in `difftest.cc:382` that should be fixed, i.e., the `plugin_device_factories` argument of `sim_t` that replaces the previous `plugin_devices`. It seems it accepts a vector of factory classes which further initiates the devices. I don't find easily how the factory is built with a base address. Hopefully you can have a try @xiaokamikami

Thank you very much for fixing cfg_t. I will continue to fix the remaining conflicts

**Comment by poemonsense** [comment]
Fixed the plugin_devices. Please help test it.

**Comment by poemonsense** [comment]
Tested with difftest against rocket, nutshell, and xiangshan. Should be able to merge.

**Pull request merged**
